---
version: '3'
services:
  binance-proxy:
    image: nightshift2k/binance-proxy:latest
    restart: unless-stopped
    container_name: binance-proxy
    hostname: binance-proxy
    ports:
      - "8090:8090"
      - "8091:8091"
    command: -v
  Bot01:
    depends_on:
      - binance-proxy
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: Bot01
    hostname: Bot01
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Bot01.log
      --db-url sqlite:////freqtrade/user_data/db/Bot01-tradesv3.sqlite
      --config /freqtrade/user_data/conf/Bot01-config.json
      --config /freqtrade/user_data/blacklist/blacklist-binance.json
      --config /freqtrade/user_data/pairlist/pairlist-volume-binance-busd.json
      --strategy NostalgiaForInfinityX
  Bot02:
    depends_on:
      - binance-proxy
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: Bot02
    hostname: Bot02
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "8081:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Bot02.log
      --db-url sqlite:////freqtrade/user_data/db/Bot02-tradesv3.sqlite
      --config /freqtrade/user_data/conf/Bot02-config.json
      --config /freqtrade/user_data/blacklist/blacklist-binance.json
      --config /freqtrade/user_data/pairlist/pairlist-volume-binance-usdt.json
      --strategy NostalgiaForInfinityX
  Bot03:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: Bot03
    hostname: Bot03
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "8082:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Bot03.log
      --db-url sqlite:////freqtrade/user_data/db/Bot03-tradesv3.sqlite
      --config /freqtrade/user_data/conf/Bot03-config.json
      --config /freqtrade/user_data/blacklist/blacklist-ftx.json
      --config /freqtrade/user_data/pairlist/pairlist-volume-ftx-usdt.json
      --strategy NostalgiaForInfinityX